# config.yaml

# See pkg/config/config.go for the full list of configuration options.
# Please keep this file empty if you don't want to override the defaults.

version: "1"

instance_id: "QjlitZRdzHKB6YIFAQHIdi"